import { Helmet } from "react-helmet";
import style from "./login.module.scss";
import { useState, useEffect } from "react";
import { validateForm } from './validation';
import { useNavigate } from "react-router-dom";
import axios from "axios";
import Cookies from "js-cookie";
import { SERVER_URL } from "../../api/config";

export default function Login() {

    const [logData, setLogData] = useState({ token: "", userId: "" });

    const navigate = useNavigate();

    const handleLogin = (formData) => {
        axios.post(`${SERVER_URL}/auth`, formData)
            .then((res) => {
                Cookies.set("token", res.data.token);
                Cookies.set("userId", res.data.userId);
                setLogData({
                    token: res.data.token,
                    userId: res.data.userId
                });
            })
            .catch((err) => {
                console.log(err);
            });
    }

    useEffect(() => {
        if (logData.token !== "") { navigate("/"); }
    }, [logData.token]);



    return (
        <>
            <Helmet>
                <title>Bienvenido | Rick y Morty | Thomas Barenghi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="theme-color" content="#379c35"></meta>
            </Helmet>
            <main>
                <header
                    className="d-flex flex-row justify-content-between align-items-center padding-lr-t1 padding-tb-30 margin-b-0"
                    style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 5, display: "flex", justifyContent: "start" }}
                >
                    
                        <img
                            src="/img/Rectangle 1.svg"
                            style={{ width: "auto" }}
                            height={40}
                            zIndex={5}
                            alt="logo"
                        />
                  
                </header>
                <HeroSection handleLogin={handleLogin} />
            </main>
        </>
    );
}

function HeroSection({ handleLogin }) {

    const [formData, setFormData] = useState({
        email: '',
        password: ''
    });
    const [errors, setErrors] = useState({});

    function handleSubmit(e) {
        e.preventDefault();
        console.log("submit")
        const formErrors = validateForm(formData);
        if (Object.keys(formErrors).length === 0) {
            handleLogin(formData);
            console.log("no hay errores")
        } else {
            setErrors(formErrors);
            console.log("hay errores")
        }
    }

    function handleInputChange(e) {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    }

    const handleByPass = () => {

        handleLogin({ email: "ejemplo@client.com", password: "12345678" })

    }


    return (
        <>
            <section
                id={style["seccion-hero"]}
                className="d-flex d-sm-flex d-md-flex d-lg-grid d-xl-grid d-xxl-grid flex-column justify-content-start align-items-center flex-sm-column justify-content-sm-start flex-md-column justify-content-md-start flex-lg-column justify-content-lg-start justify-content-xl-center align-items-xl-center justify-content-xxl-center align-items-xxl-center"
            >
                <div id={style["col1"]} />
                <div
                    id={style["col2"]}
                    className="d-flex flex-column justify-content-center align-items-start align-items-sm-start"
                >
                    <div style={{ width: "100%" }}>
                        <h1 className="titulo2-regular margin-b-0">
                            Bienvenido <strong>de nuevo</strong>
                            <br />
                        </h1>
                        <p className="body-regular color-body margin-b-40">
                            Comienza a disfrutar Rick y Morty
                            <br />
                        </p>
                    </div>
                    <form onSubmit={handleSubmit} id={style["form"]} className="d-flex flex-column">

                        <label
                            id={style["label"]}
                            className="form-label d-flex flex-column smallText-regular"
                        >
                            Correo electrónico
                            <input
                                id={style["input"]}
                                className="form-control smallText-regular"
                                type="text"
                                name="email"
                                value={formData.email}
                                onChange={handleInputChange}
                            />
                            {errors.email && <div className="error">{errors.email}</div>}
                        </label>

                        <label
                            id={style["label"]}
                            className="form-label d-flex flex-column smallText-regular"
                        >
                            Contraseña
                            <input
                                id={style["input"]}
                                className="form-control smallText-regular"
                                type="password"
                                name="password"
                                value={formData.password}
                                onChange={handleInputChange}
                            />
                            {errors.password && <div className="error">{errors.password}</div>}
                        </label>
                        <button
                            id={style["submit"]}
                            className="btn btn-primary btn1-t1 btn1"
                            type="submit"

                        >
                            Iniciar sesión
                        </button>
                        <button onClick={handleByPass} className="btn btn-primary btn1-t1 btn1" type="button">
                            Hacer ByPass
                        </button>
                    </form>
                </div>
            </section>
        </>
    )
}