export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const FAVORITE_CHARACTER = "FAVORITE_CHARACTER";
export const FILTER_CHARACTERS = "FILTER_CHARACTERS";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const CHANGE_INDEX = "CHANGE_INDEX";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const GET_CHARACTER = "GET_CHARACTER";
export const GET_FAVORITES = "GET_FAVORITES";
export const GET_PROPIOS = "GET_PROPIOS";
export const DELETE_PROPIO = "DELETE_PROPIO";


