import HeaderDefault from "../../componentes/masters/header/HeaderDefault";
import CharactersGrid from "../../componentes/characters/charactersGrid/CharactersGrid";
import style from "./home.module.scss";
import { hideHeader } from "../../componentes/modal/modal";
import { Helmet } from 'react-helmet';
import { useRef } from "react";

export default function Home() {

    const cerrarModal = (e) => { if (e.target.id === "openModal" || e.target.closest("#modalInner")) { return }; hideHeader(false, "all"); };
    const sectionRef = useRef(null);
    const scrollToSection = () => { sectionRef.current.scrollIntoView({ behavior: "smooth" }); };

    return (
        <>
            <Helmet>
                <title>Rick y Morty | Thomas Barenghi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="theme-color" content="#379c35"></meta>
            </Helmet>
            <main onClick={cerrarModal}>
                <HeaderDefault searchStatus={true} />
                <HeroSection scrollToSection={scrollToSection} />
                <section ref={sectionRef}>
                    <CharactersGrid />
                </section>

            </main>
        </>
    );
}

function HeroSection({ scrollToSection }) {
    return (
        <section
            id={style["seccion-hero"]}
            className="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-grid d-xxl-grid flex-column-reverse justify-content-start align-items-center flex-sm-column-reverse flex-md-column-reverse flex-lg-row padding-t1"
        >
            <div>
                <h1 className="titulo1-regular">
                    Descubre las aventuras de <strong>Rick y Morty</strong>
                    <br />
                </h1>
                <p className="body-regular margin-b-24">
                    ¿Estás listo para sumergirte en un mundo lleno de locura, humor
                    negro y aventuras intergalácticas? Entonces no te pierdas las
                    aventuras de Rick y Morty.
                    <br />
                </p>
                <button className="btn btn-primary btn1 btn1-t1" type="button"
                    onClick={scrollToSection}
                >
                    Conoce a los personajes
                    <br />
                </button>
            </div>
            <div className="d-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-end justify-content-xl-end justify-content-xxl-end">
                <img id={style["hero-img"]} src="/img/Group 3.svg" />
            </div>
        </section>
    )
}

